#!/usr/bin/env python3
"""
Parse a dashboard export ZIP and generate TypeScript resources code.

Extracts images from the ZIP into an assets directory and generates a
TypeScript file with proper image imports and resource objects.

Usage:
    python scripts/parse-export-zip.py <export.zip> [assets_output_dir] [ts_output_path]

Defaults:
    assets_output_dir = src/assets/exported-images
    ts_output_path    = src/content/resources/generated-resources.ts
"""
import zipfile
import json
import sys
import os
import re
import shutil


def sanitize_identifier(name: str) -> str:
    """Turn a filename into a safe TypeScript identifier."""
    return re.sub(r'[^a-zA-Z0-9_]', '_', name)


def path_to_var(path: str) -> str:
    """Generate an import variable name from a relative image path."""
    basename = os.path.basename(path)
    name, _ = os.path.splitext(basename)
    return f"img_{sanitize_identifier(name)}"


def ts_literal(value, indent: int = 0, image_map: dict | None = None) -> str:
    """Convert a Python value to a TypeScript literal string."""
    if image_map is None:
        image_map = {}

    # Raw reference wrapper (used for image imports)
    if isinstance(value, dict) and len(value) == 1 and '__raw' in value:
        return value['__raw']

    if isinstance(value, dict):
        lines = []
        for k, v in value.items():
            ts_v = ts_literal(v, indent + 2, image_map)
            lines.append(f"{' ' * (indent + 2)}{k}: {ts_v}")
        return "{\n" + ",\n".join(lines) + f"\n{' ' * indent}}}"

    if isinstance(value, list):
        items = [ts_literal(item, indent + 2, image_map) for item in value]
        if not items:
            return '[]'
        return "[\n" + ",\n".join(f"{' ' * (indent + 2)}{item}" for item in items) + f"\n{' ' * indent}]"

    if isinstance(value, str):
        if value.startswith('./images/') and value in image_map:
            return image_map[value]
        return json.dumps(value, ensure_ascii=False)

    if isinstance(value, bool):
        return 'true' if value else 'false'

    if value is None:
        return 'null'

    return str(value)


def transform_resource(resource: dict, image_map: dict) -> dict:
    """Transform a resource from dashboard-export format to shipped-code format."""
    result = dict(resource)

    # Library thumbnail imageUrl
    image_url = result.get('imageUrl')
    if isinstance(image_url, str) and image_url.startswith('./images/'):
        result['imageUrl'] = {'__raw': image_map[image_url]}

    # Featured image: uploaded -> external with imported path
    featured = result.get('featuredImage')
    if isinstance(featured, dict) and featured.get('kind') == 'uploaded':
        data_url = featured.get('dataUrl', '')
        if isinstance(data_url, str) and data_url.startswith('./images/'):
            result['featuredImage'] = {
                'kind': 'external',
                'imageUrl': {'__raw': image_map[data_url]},
                'alt': featured.get('alt', ''),
            }

    # Body blocks
    body = result.get('body')
    if isinstance(body, list):
        new_body = []
        for block in body:
            new_block = dict(block)
            block_url = new_block.get('imageUrl')
            if (
                new_block.get('kind') == 'image'
                and isinstance(block_url, str)
                and block_url.startswith('./images/')
            ):
                new_block['imageUrl'] = {'__raw': image_map[block_url]}
            # Remove helper fields not needed in shipped code
            new_block.pop('imageFileName', None)
            new_body.append(new_block)
        result['body'] = new_body

    # Remove helper fields not needed in shipped code
    result.pop('imageFileName', None)

    return result


def generate_ts(resources: list, image_map: dict, assets_dir: str) -> str:
    """Generate the full TypeScript source file."""
    # Sort imports by variable name for stability
    imports = sorted(
        (
            f"import {var_name} from '{assets_dir}/{os.path.basename(path)}';"
            for path, var_name in image_map.items()
        ),
        key=lambda s: s,
    )

    transformed = [transform_resource(r, image_map) for r in resources]

    resources_ts = ts_literal(transformed, indent=2)

    lines = [
        "// Auto-generated by scripts/parse-export-zip.py",
        "// Do not edit manually — regenerate from the export ZIP instead.",
        "import type { EducationResource } from '../../domain/resources/types';",
        "",
        *imports,
        "",
        "export const generatedResources = " + resources_ts + " satisfies EducationResource[];",
        "",
    ]

    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python scripts/parse-export-zip.py <export.zip> [assets_output_dir] [ts_output_path]")
        sys.exit(1)

    zip_path = sys.argv[1]
    assets_dir = sys.argv[2] if len(sys.argv) > 2 else 'src/assets/exported-images'
    ts_path = sys.argv[3] if len(sys.argv) > 3 else 'src/content/resources/generated-resources.ts'

    if not os.path.isfile(zip_path):
        print(f"Error: ZIP file not found: {zip_path}")
        sys.exit(1)

    # Create assets directory
    os.makedirs(assets_dir, exist_ok=True)

    with zipfile.ZipFile(zip_path, 'r') as zf:
        # Read data.json
        if 'data.json' not in zf.namelist():
            print("Error: data.json not found in ZIP.")
            sys.exit(1)

        bundle = json.loads(zf.read('data.json'))
        changes = bundle.get('changes', {})
        resources = changes.get('educationMaterials', [])

        # Extract images
        image_map = {}
        for name in zf.namelist():
            if name.startswith('images/'):
                # Copy to assets directory
                dest_name = os.path.basename(name)
                dest_path = os.path.join(assets_dir, dest_name)
                with zf.open(name) as src, open(dest_path, 'wb') as dst:
                    shutil.copyfileobj(src, dst)

                # Map the relative path from data.json to an import variable
                rel_path = f"./{name}"
                image_map[rel_path] = path_to_var(name)
                print(f"  Extracted: {name} -> {dest_path}")

    if not resources:
        print("Warning: No education materials found in export.")
    else:
        print(f"  Found {len(resources)} material(s).")

    # Generate TypeScript
    # Compute the relative import path from the TS file to the assets dir
    ts_dir = os.path.dirname(ts_path) or '.'
    assets_rel = os.path.relpath(assets_dir, ts_dir).replace('\\', '/')
    # Ensure it starts with ./ or ../
    if not assets_rel.startswith('.'):
        assets_rel = './' + assets_rel

    ts_source = generate_ts(resources, image_map, assets_rel)

    os.makedirs(os.path.dirname(ts_path) or '.', exist_ok=True)
    with open(ts_path, 'w', encoding='utf-8') as f:
        f.write(ts_source)

    print(f"\nGenerated: {ts_path}")
    print(f"\nNext steps:")
    print(f"  1. Review the generated file.")
    print(f"  2. Commit the generated TypeScript file and extracted image assets.")
    print(f"  3. Run 'pnpm run check' to verify.")


if __name__ == '__main__':
    main()
